### ISSUE TITLE
This plugin does not work.

### ISSUE THREAD

**Issue by aimran50** [EconomatDesArmees/redmine_easy_wbs#3]
After installation and activating the module, tab shows "translation missing: en.easy_wbs.button_project_menu".

**Comment by xiaoruiguo** [comment]
ActionView::Template::Error (no implicit conversion of Symbol into String):

config/initializers/10-patches.rb:215:in `rails_asset_id'
  config/initializers/10-patches.rb:200:in `asset_path_with_asset_id'
  app/helpers/application_helper.rb:1365:in `stylesheet_link_tag'
  plugins/easy_wbs/app/views/easy_wbs/index.html.erb:241:in `block in _plugins_easy_wbs_app_views_easy_wbs_index_html_erb__497914210210918168_70041907790820'
  plugins/easy_wbs/app/views/easy_wbs/index.html.erb:76:in `_plugins_easy_wbs_app_views_easy_wbs_index_html_erb__497914210210918168_70041907790820'
  plugins/easy_wbs/app/controllers/easy_wbs_controller.rb:21:in `block (2 levels) in index'
  plugins/easy_wbs/app/controllers/easy_wbs_controller.rb:20:in `index'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
